version: '2'
services:
  mypostgres:
    image: postgres
    restart: always
    environment:
     - POSTGRES_PASSWORD=123456
     - POSTGRES_USER=postgres
     - POSTGRES_DB=library
    volumes:
     - /opt/pgdata:/var/lib/postgresql/data
  web:
    image: esempla/web
    restart: always
    environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://mypostgres/library
       SPRING_DATASOURCE_USERNAME: postgres
       SPRING_DATASOURCE_PASSWORD: 123456
    ports:
    - "8081:8081"
    depends_on:
    - mypostgres